---
title: "02 Phenology"
output: rmarkdown::html_vignette
fig_caption: yes
vignette: >
  %\VignetteIndexEntry{Vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_knit$set(root.dir = here::here()) # knit from project directory
knitr::opts_chunk$set(
  collapse = TRUE,
  dpi = 300,
  cache = T,
  comment = "#>",
  warning = F,
  message = F,
  out.width = "100%",
  fig.align = "left"
)
```

```{r setup}
library(phenotwitter)
theme_set(ggthemes::theme_few())
```

# Twitter time series

```{r}
df_user_num <- read_user_num()
plot_user_num(df_user_num = df_user_num, save = T)
```

```{r, eval = F}
df_ts_tw <- calc_time_series(df_tweet = df_tweet, df_user_num = df_user_num, option = "twitter")
usethis::use_data(df_ts_tw, overwrite = T)
```

```{r}
plot_time_series(df_ts_tw = df_ts_tw, option = "twitter", save = T)
summ_time_series_twitter(df_ts_tw = df_ts_tw)
```

Processing steps
- Standardize to approximately between 0 and 1
- Whittaker smoothing with gap filling

```{r, eval = F}
df_ts_tw_proc <- calc_time_series(df_tweet = df_tweet, df_user_num = df_user_num, option = "twitter", process = T)
usethis::use_data(df_ts_tw_proc, overwrite = T)
```

```{r}
plot_time_series(df_ts_tw = df_ts_tw_proc, option = "twitter", process = T, save = T)
```

```{r}
summ_ts_spring(df_ts_tw = df_ts_tw)
```

# NAB time series
```{r, eval = F}
df_nab <- read_nab()
plot_nab_map(df_nab = df_nab, save = T)
```

```{r, eval = F}
df_ts_nab <- calc_time_series(df_nab = df_nab, option = "nab")
usethis::use_data(df_ts_nab, overwrite = T)

tidy_remove_sample(df = df_nab, option = "nab")

plot_time_series(df_ts_nab = df_ts_nab, option = "nab", save = T)
```

Processing steps
- Standardize to approximately between 0 and 1 for each station
- Average over all stations
- Whittaker smoothing with gap filling

```{r, eval = F}
df_ts_nab_proc <- calc_time_series(df_nab = df_nab, option = "nab", process = T)
usethis::use_data(df_ts_nab_proc, overwrite = T)
```

```{r}
plot_time_series(df_ts_nab = df_ts_nab_proc, option = "nab", process = T, save = T)
```

# Compare time series
```{r}
(p_ts_compare <- plot_time_series(df_ts_tw = df_ts_tw_proc, df_ts_nab = df_ts_nab_proc, option = "compare", save = T))
```

## Spatiotemporal analysis
```{r, eval = F}
df_st_tw <- calc_spatial_time_series(df_tweet = df_tweet, df_user_num = df_user_num, option = "twitter")
usethis::use_data(df_st_tw, overwrite = T)

tidy_remove_sample(df_tweet, option = "twitter")
```

```{r}
df_st_metric_tw <- calc_spatiotemporal_metrics(df_st = df_st_tw)
plot_spatial_time_series(df_st_tw = df_st_tw, df_st_metric_tw = df_st_metric_tw, save = T, option = "twitter")
usethis::use_data(df_st_metric_tw, overwrite = T)
```

```{r, eval = F}
df_st_nab <- calc_spatial_time_series(df_nab = df_nab, option = "nab")
usethis::use_data(df_st_nab, overwrite = T)
```

```{r}
df_st_metric_nab <- calc_spatiotemporal_metrics(df_st = df_st_nab)
plot_spatial_time_series(df_st_nab = df_st_nab, df_st_metric_nab = df_st_metric_nab, save = T, option = "nab")
usethis::use_data(df_st_metric_nab, overwrite = T)
```

```{r}
(p_st_compare <- plot_spatial_time_series(df_st_tw = df_st_tw, df_st_nab = df_st_nab, df_st_metric_tw = df_st_metric_tw, df_st_metric_nab = df_st_metric_nab, save = T, option = "compare"))

(p_metrics_compare <- plot_phenology_metrics_compare(df_st_metric_tw = df_st_metric_tw %>% filter(!state %in% c("AK", "HI")), df_st_metric_nab = df_st_metric_nab, metricoi = "mos", save = T))
```

```{r}
plot_phenology_compare(p_ts_compare = p_ts_compare, p_st_compare = p_st_compare, p_metrics_compare = p_metrics_compare, save = T)
```
