---
title: "03 Ideological structure"
output: rmarkdown::html_vignette
fig_caption: yes
vignette: >
  %\VignetteIndexEntry{Vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_knit$set(root.dir = here::here()) # knit from project directory
knitr::opts_chunk$set(
  collapse = TRUE,
  dpi = 300,
  cache = T,
  comment = "#>",
  warning = F,
  message = F,
  out.width = "100%",
  fig.align = "left"
)
```

```{r setup}
library(phenotwitter)
theme_set(ggthemes::theme_few())
```

# Define subgroups of users
```{r}
(p_subgroup_venn <- plot_subgroup_venn(save = T))
```

# sample and code tweets in subgroups
```{r, eval = F}
ls_df_group_sample <- tidy_subgroup_sample(df_tweet = df_tweet, writecsv = T)
usethis::use_data(ls_df_group_sample)
# manually label sampled tweets here
ls_df_group_label <- read_subgroup_label(valid = F)
ls_df_group_valid <- read_subgroup_label(valid = T)
usethis::use_data(ls_df_group_valid)
```

```{r}
set.seed(1)
ls_df_group_valid$pollen %>%
  sample_n(3) %>%
  pull(text)
ls_df_group_valid$`pollen-temperature` %>%
  sample_n(3) %>%
  pull(text)
ls_df_group_valid$`pollen-climate` %>%
  sample_n(3) %>%
  pull(text)
```

# get ideology of users in subgroups
```{r, eval = F}
calc_user_ideology(ls_df_group_sample)
ls_df_user_ideology <- read_user_ideology()
usethis::use_data(ls_df_user_ideology)
```

```{r, eval = F}
ls_df_group_ideology <- calc_group_ideology(ls_df_group_sample = ls_df_group_sample, ls_df_group_valid = ls_df_group_valid, ls_df_user_ideology = ls_df_user_ideology)
usethis::use_data(ls_df_group_ideology)
```

```{r}
bind_rows(ls_df_group_valid) %>% 
  distinct(user_screen_name) %>% 
  inner_join(bind_rows(ls_df_user_ideology)%>%
    filter(ideology != 999) %>%
    filter(!is.na(ideology)) %>%
    filter(is.finite(ideology)), by = c("user_screen_name"= "user")) %>% 
  nrow()
```

```{r}
```

```{r}
df_group_sample_size <- ls_df_group_ideology$sample_size
df_group_sample_size
summ_group_sample_size(df_group_sample_size = df_group_sample_size, option = "temperature")
summ_group_sample_size(df_group_sample_size = df_group_sample_size, option = "climate")
```

# ideological structure in attribution
```{r}
df_group_ideology <- ls_df_group_ideology$sample
df_summ_group_ideology <- summ_group_ideology(df_group_ideology)
df_summ_group_ideology
```

```{r}
p_ideology_density <- plot_ideology_density(
  df_group_ideology = df_group_ideology,
  df_summ_group_ideology = df_summ_group_ideology,
  save = T
)
```

```{r}
df_ideo_cond_prob <- calc_ideo_cond_prob(df_group_ideology = df_group_ideology, df_group_sample_size = df_group_sample_size, R = 1000)
p_ideo_cond_prob_temperature <- plot_ideo_cond_prob(df_ideo_cond_prob = df_ideo_cond_prob, option = "temperature", R = 1000, save = T)
p_ideo_cond_prob_temperature
p_ideo_cond_prob_climate <- plot_ideo_cond_prob(df_ideo_cond_prob = df_ideo_cond_prob, option = "climate", R = 1000, save = T)
p_ideo_cond_prob_climate
```

```{r}
plot_ideology_structure(
  p_subgroup_venn = p_subgroup_venn,
  p_ideology_density = p_ideology_density,
  p_ideo_cond_prob_temperature = p_ideo_cond_prob_temperature,
  p_ideo_cond_prob_climate = p_ideo_cond_prob_climate,
  save = T
)
```
